### PR TITLE
[WIP] Documentation

### PR DESCRIPTION
**Pull request by tarzzz**
Initialized the Sphinx documentation module/

### CODE REVIEW

**Comment by moorepants** [comment]
Tarun, this looks fine. But why do you have all the test commits in this PR? I would make a new branch and put the two sphinx files in it. You will have duplicate history trees if you leave these old commits in this PR.

**Comment by moorepants** [comment]
This is ready to merge as soon as you get rid of these duplicate commits for the shape tests.

**Comment by chrisdembia** [comment]
He removed the files by an additional commit; do you mean to instead remove commits themselves from the PR? How do you do that?

**Comment by tarzzz** [comment]
Should I make another PR without duplicate commit history?

**Pull request closed without merging**
