### PR TITLE
Js docstrings

### PR DESCRIPTION
**Pull request by tarzzz**

### CODE REVIEW

**Comment by moorepants** [comment]
Travis is actually failing: https://travis-ci.org/PythonDynamics/pydy-viz/builds/11450950

The bin/test command is exiting with zero even though the tests fail.

**Comment by moorepants** [comment]
I didn't look at all the details of this, but this seems complete in itself, even if you don't have a docstring for everything. This looks fine to merge.

**Comment by tarzzz** [comment]
The ts failing only because master isnt merged in it.  I will do that and
then it will pass

**Comment by moorepants** [comment]
These three commits don't affect any tests that are run on travis, so it can be merged as is.

**Pull request closed without merging**
