### PR TITLE
Default light

### PR DESCRIPTION
**Pull request by tarzzz**

### CODE REVIEW

**Comment by moorepants** [comment]
This PR seems fine. The only addition could be adding a test to check that this kwarg was set correctly. Is it tested?

**Comment by tarzzz** [comment]
Sorry, I didnt get you ..

**Comment by moorepants** [comment]
Sorry you didn't get me?

**Comment by tarzzz** [comment]
What test are you rwferring to.i mean I have pointlight tests.

**Comment by moorepants** [comment]
Here you add a new kwarg to Scene (i think). Do you test this functionality?

**Comment by tarzzz** [comment]
@PythonDynamics/visualization I havent tested this functionality. i am going to create another PR for that.
Merged this one.

**Comment by moorepants** [comment]
Please don't create new PRs for tests that should belong with this function in the future. The reason is that you just merged untested code into master. What if this had a bug in it? Always merge "tested" code into master unless you really just don't plan to ever write a test for it (which ideally would never be the case).

**Pull request merged**
