### PR TITLE
Added coverage to travis and Javascript testing.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
This may be working, not sure. I don't know what phantom-jasmine should be outputting.

**Comment by moorepants** [comment]
There is still no output from the jasmine tests. Do the tests work locally for you?

**Comment by moorepants** [comment]
Why are these commits in master already?

**Comment by tarzzz** [comment]
Nothing on local either. Just gives no output.

**Pull request closed without merging**
