### PR TITLE
Release 0.1.0 sphinx doc

### PR DESCRIPTION
**Pull request by tarzzz**
Can be merged, once we have a PyPI repository ready, and a tar.gz source added on some server

### CODE REVIEW

**Comment by moorepants** [comment]
What is the status of this?

**Comment by tarzzz** [comment]
It needs to be finished.

**Comment by moorepants** [comment]
This isn't a priority for the tutorial, but if it is close to done it would be nice to have in the first release.

**Comment by moorepants** [comment]
Is this ready for the 0.1.0 release?

**Comment by tarzzz** [comment]
Yes. It does not contain tutorials though, only basic documentation and module reference.
I think we can keep it for 0.1.0 and add tutorials later.

**Comment by moorepants** [comment]
If the basics are there, then we can merge it I suppose. But it isn't required for this first release.

**Comment by moorepants** [comment]
Make sure you've added these files to the MANIFEST.in.

**Comment by tarzzz** [comment]
These files are in manifest. Merging #55

**Pull request merged**
